"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from shutil import which

# Load environment variables from the .env file
load_dotenv()

# Basic Django settings
DEBUG = os.getenv("DJANGO_DEBUG")
ALLOWED_HOSTS = ['*']

# API settings
API_SETTINGS = {
    "API_USERNAME": os.getenv("API_USERNAME"),
    "API_PASSWORD": os.getenv("API_PASSWORD"),
    "API_BASE_URL": os.getenv("API_BASE_URL"),
    "API_AUTH_URL": os.getenv("API_AUTH_URL"),
    "API_LOANREQUEST_URL": os.getenv("API_LOANREQUEST_URL"),
    "API_HIST_URL": os.getenv("API_HIST_URL"),
    "API_TOKEN": os.getenv("API_TOKEN"),
    "API_USER_ID": os.getenv("API_USER_ID")
}

# Set the base directory of the project
BASE_DIR = Path(__file__).resolve().parent.parent

# Security settings
SECRET_KEY = os.getenv("SECRET_KEY")  # Secret key should remain secret

# Authentication configuration
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Standard authentication
    'app.views.views_auth.EmailBackend',  # Email-based authentication
]

# Installed apps
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'tailwind',
    'theme'
]

# Static files directories
STATICFILES_DIRS = [
    BASE_DIR / "theme" / "static"
]
# Static files (CSS, JavaScript, Images) settings
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' 


# Tailwind CSS settings
TAILWIND_APP_NAME = 'theme'

# Middleware configuration
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# URL configuration
ROOT_URLCONF = 'project.urls'

# Templates settings
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'app' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI and ASGI applications
WSGI_APPLICATION = 'project.wsgi.application'
ASGI_APPLICATION = 'project.asgi.application'

# Database configuration
DB_USERNAME = os.getenv("DB_USERNAME")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_SERVER = os.getenv("DB_SERVER")
DB_NAME = os.getenv("DB_NAME")
DB_PORT = os.getenv("DB_PORT")
DB_DRIVER = os.getenv("DB_DRIVER")
DATABASE_URL = os.getenv("DATABASE_URL")
DB_ENGINE = os.getenv("DB_ENGINE")

DATABASES = {
    'default': {
        'ENGINE': 'mssql',  
        'NAME': DB_NAME,   
        'USER': DB_USERNAME,        
        'PASSWORD': DB_PASSWORD,    
        'HOST': DB_SERVER,
        'PORT': DB_PORT,
        'OPTIONS': {
            'driver': "ODBC Driver 18 for SQL Server",
            'Encrypt': 'yes',
            'TrustServerCertificate': 'no',
            'Connection Timeout': 30,
        },
    }
}


# Password validation settings
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization settings
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Path to the NPM executable
NPM_BIN_PATH = which("npm")

# Custom user model
AUTH_USER_MODEL = 'app.UserProfile'

# Redirects after login and logout
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = '/logout/'
