# Generated by Django 5.1.6 on 2025-02-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='amount',
            field=models.IntegerField(max_length=10),
        ),
    ]
