# Generated by Django 5.1.6 on 2025-02-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_loanrequest_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='term',
            field=models.IntegerField(max_length=10),
        ),
    ]
