# Generated by Django 5.1.6 on 2025-02-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_loanrequest_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='franchise',
            field=models.CharField(choices=[('1', 'Franchise'), ('0', 'Non-Franchise')], max_length=1),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='low_doc',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='naics',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='new',
            field=models.CharField(choices=[('1', 'New'), ('0', 'Existing')], max_length=1),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='no_emp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='rev_line_cr',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='rural',
            field=models.CharField(choices=[('0', 'Urban'), ('1', 'Rural'), ('None', 'Undefined')], max_length=4),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='term',
            field=models.IntegerField(),
        ),
    ]
