# Generated by Django 5.1.6 on 2025-02-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_loanrequest_amount_alter_loanrequest_franchise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('advisor', 'Advisor')], default='client', max_length=20),
        ),
    ]
