# Generated by Django 5.1.6 on 2025-02-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='low_doc',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='naics',
            field=models.CharField(max_length=2),
        ),
    ]
